<?php

/**
 * Implements hook_menu().
 */
function allegro_menu() {
  $items['admin/allegro'] = array(
    'title' => 'Allegro',
    'page callback' => 'drupal_get_form',
    'access arguments' => array('administer allegro'),
    'page arguments' => array('allegro_settings_form'),
    'file' => 'allegro.admin.inc',
  );
  $items['admin/allegro/settings'] = array(
    'title' => 'Settings',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function allegro_permission() {
  return array(
    'administer allegro' => array(
      'title' => t('Administer Allegro'),
    ),
  );
}

/**
 * Connect to Allegro WebAPI and returns SoapClient object.
 *
 * @param  bool $login
 *   Log into the Soap service.
 * @param  bool $cache
 *   Whether to reset the internal allegro_client cache.
 *
 * @return mixed
 *   Returns Allegro client object when success, false otherwise.
 */
function allegro_client($login = TRUE, $reset = FALSE) {
  if (!$reset) {
    $allegro = &drupal_static(__FUNCTION__);
  }

  if (empty($allegro) || $allegro->logged != $login) {
    try {
      $allegro = new Allegro();

      $allegro->userLogin = variable_get('allegro_login');
      $allegro->userPassword = variable_get('allegro_password');
      $allegro->webapiKey = variable_get('allegro_webapikey');
      $allegro->countryCode = variable_get('allegro_country_code');

      if ($login) {
        $allegro->login();
      }
    }
    catch (SoapFault $e) {
      if (module_exists('dblog') && user_access('access site reports')) {
        drupal_set_message(t('An error occured while connecting to WebAPI service. Check <a href="@watchdog-url">watchdog</a> for more informations.', array('@watchdog-url' => url('admin/reports/dblog'))), 'error');
      }
      else {
        drupal_set_message(t('An error occured while connecting to WebAPI service. Check logs for more informations.'), 'error');
      }
      watchdog_exception('allegro', $e);
      unset($allegro);
    }
  }

  return !empty($allegro) ? $allegro : FALSE;
}

/**
 * Test connection to Allegro WebAPI service.
 *
 * @param  string $login
 *   Service login.
 * @param  string $password
 *   Service password.
 * @param  string $webapikey
 *   API key to service.
 * @param  int $countryCode
 *   Country code of targeted market.
 *
 * @return bool
 *   True when connection is successfull, false otherwise.
 */
function allegro_test_connection($login = NULL, $password = NULL, $webapikey = NULL, $countryCode = NULL) {
  if (!$login) {
    $login = variable_get('allegro_login');
  }
  if (!$password) {
    $password = variable_get('allegro_password');
  }
  if (!$webapikey) {
    $webapikey = variable_get('allegro_webapikey');
  }
  if (!$countryCode) {
    $countryCode = variable_get('allegro_country_code');
  }

  if (!$login || !$password || !$webapikey || !$countryCode) {
    return FALSE;
  }

  try {
    Allegro::testConnection($login, $password, $webapikey, $countryCode);
    return TRUE;
  }
  catch (SoapFault $e) {
    return FALSE;
  }
}

/**
 * Convert object to array.
 *
 * @param object $object
 *
 * @return array
 */
function allegro_object2array($object) {
  if (!is_object($object) && !is_array($object)) {
    return $object;
  }
  if (is_object($object)) {
    $object = get_object_vars($object);
  }
  return array_map('allegro_object2array', $object);
}

/*
 * Unused.
 * Resizes images to pass Allegro validation.
 */
function allegro_resize_image($url) {
  $image = file_get_contents($url);

  // właśnie tutaj używamy Base64 ręcznie, ale nigdzie indziej!
  while (strlen(base64_encode($image)) > 200000) {
    $temp = imagecreatefromstring($image);
    $x = ceil(0.9 * imagesx($temp));
    $y = ceil(0.9 * imagesy($temp));

    $image = imagecreatetruecolor($x, $y);
    imagecopyresized($image, $temp, 0, 0, 0, 0, $x, $y, imagesx($temp), imagesy($temp));

    imagejpeg($image, 'temp.jpg', 75);
    $image = file_get_contents('temp.jpg');
    unlink('temp.jpg');
  }

  return $image;
}
